### ISSUE TITLE
SyntaxError prevents homebridge from launch

### ISSUE THREAD

**Issue by daniestermann** [dinmammas/homebridge-robonect#3]
My homebridge instance fails to boot due to an exception in the homebridge-robonect module.
Is this connected to the new 1.2 firmware?

**Exception**
```
Loaded plugin: homebridge-robonect@1.0.22
Registering accessory 'homebridge-robonect.HomebridgeRobonect'
...
Homebridge is running on port 51826.
...
SyntaxError: Unexpected end of JSON input
     at JSON.parse (<anonymous>)
     at Request._callback (/usr/local/lib/node_modules/homebridge-robonect/index.js:47:25)
     at Request.self.callback (/usr/local/lib/node_modules/homebridge-robonect/node_modules/request/request.js:185:22)
     at Request.emit (events.js:315:20)
     at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-robonect/node_modules/request/request.js:1154:10)
     at Request.emit (events.js:315:20)
     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-robonect/node_modules/request/request.js:1076:12)
     at Object.onceWrapper (events.js:421:28)
     at IncomingMessage.emit (events.js:327:22)
     at endReadableNT (_stream_readable.js:1201:12)
Got SIGTERM, shutting down Homebridge...
```

**homebridge-robonect configuration**
```
        {
            "accessory": "HomebridgeRobonect",
            "name": "Rasenmäher",
            "mower": "Husqvarna",
            "model": "105",
            "robonect-card": "HX",
            "serial-number": "xxxxxxxxx",
            "getUrl": "http://admin:xxxxx@192.168.86.180"
        }
```

**Versions**
- Raspbian GNU/Linux Stretch (9)
- homebridge-robonect 1.0.22
- Node.js v13.14.0
- npm v6.14.5
- Robonect Firmware v1.2 (Kompiliert 14.07.2020 10:32)

What else do you need to know?

**Comment by daniestermann** [comment]
After updating the robonect firmware to daily build V1.2_Fix **2020-08-20**, this issue no longer happens. 
Or was it just the reboot  of the mower?

**Comment by dinmammas** [comment]
It's related to a bug in the Robonect firmware, but also related to my lazy programming ;) I will strive to do better.
